### ISSUE TITLE
Parâmetros number

### ISSUE THREAD

**Issue by srzillig** [bh2tech/bh2_apix_ms#1]
Alguns parâmetros como: Perc50TempoExpUsuarioIntra, ValorReceita, QtdTransacoes, etc são tipados como "number" e quando eu envio um int 0 recebo "must be a positive number" e se eu não tiver feito nenhuma transação em um mês ou não tiver feito uma devolução em um mês o que eu faço?

**Comment by vagnerlborges** [comment]
@srzillig, você pode enviar como "zero" quando não tiver transacionado. Aplicamos uma correção que resolve este bug, obrigado pela sua contribuição. 👍🏻
