### ISSUE TITLE
Problemas ao Buildar pelo .Dockerfile

### ISSUE THREAD

**Issue by srzillig** [bh2tech/bh2_apix_ms#5]
Estou tentando buildar o projeto pelo .Dockerfile

![image](https://user-images.githubusercontent.com/31997176/115250319-d2e10900-a0ff-11eb-95f2-c15e378876ec.png)

E estou tomando esse erro: 
 
![image](https://user-images.githubusercontent.com/31997176/115250357-db394400-a0ff-11eb-9259-0e7ea3ef480e.png)

**Comment by henriquebizarria** [comment]
Pull Request para esse problema já feito:
https://github.com/bh2tech/bh2_apix_ms/pull/6
Aguardado revisão.

**Comment by vagnerlborges** [comment]
@srzillig problema foi corrigido. Obrigado pela contribuição.
