### ISSUE TITLE
Atualização de Padrão Documento APIX

### ISSUE THREAD

**Issue by srzillig** [bh2tech/bh2_apix_ms#7]
Dia 4 foi feita algumas atualizações no padrão dos documentos auxiliares do pix.

 O projeto já contempla essa atualização ou seria necessário um patch para se adequar a atualização?

![image](https://user-images.githubusercontent.com/31997176/117334717-b9b2b900-ae70-11eb-8794-3178ca2c0981.png)

**Comment by vagnerlborges** [comment]
Olá,

Estamos confirmando a mudança já que o ajuste feito x comunicado enviado não esta batendo. Assim que tiver um retorno vamos subir as atualizações.

![image](https://user-images.githubusercontent.com/36044725/117720595-37e6c680-b1b5-11eb-957e-5ea31a07dd63.png)

![image](https://user-images.githubusercontent.com/36044725/117720628-47660f80-b1b5-11eb-9f79-ef66b01a58f6.png)
